---
name: CI (pip)
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install with dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[test]"

      - name: Test with pytest
        run: |
          coverage run --source=. -m pytest 
